Adding a vendor property to extract host_ip address vendor.intel.ipaddr
projectceladon/device-intel-sepolicy pull request #111
Opened 2021-08-19 14:38 UTC by RajaniRanjan

Signed-off-by: RajaniRanjan <rajani.ranjan@intel.com>

2021-08-19 15:03 UTC, balajim001 approved these changes
LGTM

2021-08-24 06:40 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3653

2021-08-26 10:37 UTC, sgnanase approved these changes

2021-08-26 10:38 UTC, sgnanase requested changes
Please add Tracked-On:

2021-08-26 10:48 UTC, sgnanase approved these changes

2021-08-26 17:30 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-celr - r1 (caas), build-celr - r1 (caas_bm), build-celr - r1 (caas_cfc), build-celr - r2 (r2_caas), build-celr - r2 (r2_caas_bm), build-celr - r2 (r2_caas_dev) - extra

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3666

2021-08-27 08:34 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-celr - r1 (caas), build-celr - r1 (caas_bm), build-celr - r1 (caas_cfc), build-celr - r2 (r2_caas), build-celr - r2 (r2_caas_bm), build-celr - r2 (r2_caas_dev) - extra

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3667

2021-08-27 09:50 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3674

2021-08-30 07:30 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3681

2021-08-30 07:39 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3682

2021-08-30 15:41 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3685

Done by "Ranjan, Rajani" <rajani.ranjan@intel.com>

2021-08-31 05:21 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2024

Done by "Ranjan, Rajani" <rajani.ranjan@intel.com>

2021-08-31 09:37 UTC, merged

2021-08-31 09:38 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Ranjan, Rajani" <rajani.ranjan@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2551