Allow Sensor HAL to Create VSOCK.
projectceladon/device-intel-sepolicy pull request #152
Opened 2021-12-31 10:46 UTC by vilasrk

Tracked-On:
Signed-off-by: vilasrk <vilas.r.k@intel.com>

2022-01-10 13:31 UTC, JaikrishnaNemallapudi approved these changes
LGTM

2022-01-11 01:10 UTC, ceiba1985 commented on sensors/mediation/sensor_hal_default.te
> +#dontaudit hal_sensors_default default_prop:file { open read getattr map };
can you delete these comment sentences?

2022-01-11 03:01 UTC, vilasrk commented on sensors/mediation/sensor_hal_default.te
> +#dontaudit hal_sensors_default default_prop:file { open read getattr map };
done

2022-01-11 12:23 UTC, rajucm2007 requested changes

2022-01-11 12:23 UTC, rajucm2007 commented on sensors/mediation/sensor_hal_default.te
check, may be not require

2022-01-12 04:53 UTC, rajucm2007 approved these changes
Looks good to me

2022-01-12 05:07 UTC, JaikrishnaNemallapudi approved these changes
LGTM

2022-01-12 05:28 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/194

2022-01-12 05:31 UTC, ceiba1985 approved these changes

2022-01-12 05:33 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/195

2022-01-12 05:55 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/196

2022-01-12 08:49 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:cancelled Generate multi manifest original json

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/197

2022-01-19 06:57 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/212

2022-01-19 07:27 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/214

2022-01-19 07:28 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/215

2022-01-19 07:34 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/216

2022-01-19 07:51 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/217

2022-01-19 13:10 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-celr - r1 (caas), build-celr - r1 (caas_bm), build-celr - r1 (caas_cfc), build-celr - r2 (r2_caas), build-celr - r2 (r2_caas_bm) - extra

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/218

2022-03-15 05:52 UTC, closed without merging