Fix SELinux error for mediatranscoding.
projectceladon/device-intel-sepolicy pull request #200
Opened 2022-10-26 02:41 UTC by chenyanxzhu

Tracked-On: OAM-104121
Signed-off-by: chenyanxzhu <chenyanx.zhu@intel.com>

2022-11-02 04:36 UTC, dyang23 approved these changes

2022-11-02 09:14 UTC, JeevakaPrabu requested changes
Please provided detailed information on the issue and how the change is fixing the issue.
Please follow the commit message convention
https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/
https://cbea.ms/git-commit/

2022-11-03 06:44 UTC, JeevakaPrabu approved these changes

2022-11-03 06:47 UTC, swaroopbalan approved these changes

2022-11-03 06:49 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/154

2022-11-03 17:42 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/155

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2022-11-03 18:12 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-premerge/builds/86

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2022-11-03 20:14 UTC, merged

2022-11-03 20:15 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_stable-mergerequest/builds/64