Fix EVS sample driver not getting started as service
projectceladon/device-intel-sepolicy pull request #228
Opened 2023-04-26 10:04 UTC by pillai45

EVS sample driver not getting started as service due to missing sepolicies

Changes done to fix the issue:
- Allow carservice_app with service find rights
- Allow carservice_app with open, read and search access for sysfs dir
- Allow carservice_app with search access for data folder

Tracked-On: OAM-108953

2023-04-27 04:31 UTC, JeevakaPrabu requested changes
please check the commit "Fix EVS sample driver not getting started as service" as it has patch file instead of modification to the file_contexts and carservice_app.te

2023-04-27 04:52 UTC, JeevakaPrabu approved these changes

2023-04-27 05:03 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/52

2023-04-27 06:02 UTC, James-Zzz approved these changes
LGTM

2023-04-27 06:05 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/54

2023-04-27 06:14 UTC, swaroopbalan approved these changes

2023-04-27 06:22 UTC, cchen111 approved these changes
Looks good to me.

2023-04-27 06:25 UTC, cchen113 approved these changes
Looks good to me.

2023-04-27 10:59 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (caas), build-cels - r1 (caas_sriov), build-cels - r1 (celadon_ivi), build-cels - r2 (r2_caas), build-cels - r2 (r2_caas_dev) - extra, build-cels - r2 (r2_caas_sriov), build-cels - r2 (r2_celadon_ivi)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/55

2023-04-27 15:52 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/57

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2023-04-27 21:12 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/32

Done by "Pillai, Venkatesh" <venkatesh.pillai@intel.com>

2023-04-28 04:02 UTC, merged

2023-04-28 04:03 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cactusi@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/36