[CIV][Android-T]debugfs neverallow violation fix
projectceladon/device-intel-sepolicy pull request #233
Opened 2023-07-13 00:22 UTC by vdanix

Fix for Below CTS CtsSecurityHostTestCases
    SELinuxNeverallowRulesTest#testNeverallowRules987
    SELinuxNeverallowRulesTest#testNeverallowRules1004

    Fix is taken from below smr0

    projectceladon/device-intel-sepolicy#197

Tracked-On: OAM-111164

2023-07-13 00:23 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-13 00:24 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-13 00:34 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-07-13 02:44 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-14 10:02 UTC, kaushlen approved these changes

2023-07-17 05:27 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/5191

2023-07-17 15:43 UTC, JeevakaPrabu requested changes
Please port the patch as is. No changes in commit message, signed-off and author.

No need to have branch name as prefix in commit message

2023-07-18 06:16 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-18 06:18 UTC, vdanix commented
> Please port the patch as is. No changes in commit message, signed-off and author.
> 
> No need to have branch name as prefix in commit message

Ported the patch as is. with original without changing in commit message, signed-off and author..

2023-07-18 06:54 UTC, JeevakaPrabu approved these changes

2023-07-18 09:09 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-18 13:21 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/5192

Done by "Dani, VishwanathX" <vishwanathx.dani@intel.com>

2023-07-19 05:21 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/3018

Done by "Dani, VishwanathX" <vishwanathx.dani@intel.com>

2023-07-19 10:04 UTC, merged

2023-07-19 10:05 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Dani, VishwanathX" <vishwanathx.dani@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/3377