Add selinux genfscon rules for suspend
projectceladon/device-intel-sepolicy pull request #234
Opened 2023-07-13 06:26 UTC by bkothapx

Suspend is Android-T added new VTS test case,
which is trying to verify genfs rules for
Unlabeled wakeup nodes found, your device is likely missing device/oem specific selinux genfscon rules for suspend. Please review and add the following generated rules to the device specific genfs_contexts:
genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:02/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:03/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0c/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:01/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:04/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:05/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:07/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:08/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:09/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0a/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0b/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/pci0000:00/0000:00:08.0/usb1/1-2/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/LNXSYSTM:00/LNXPWRBN:00/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/pnp0/00:03/rtc/rtc0/alarmtimer.1.auto/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/pci0000:00/0000:00:09.0/usb1/1-2/wakeup u:object_r:sysfs_wakeup:s0 genfscon sysfs /devices/pnp0/00:03/wakeup u:object_r:sysfs_wakeup:s0

Tracked-On: OAM-111173

2023-07-13 06:27 UTC, sysopenci commented
Improper Commit Message
Jira issue not in ['bug','improvement'],
    make sure jira issue is of type bug or improvement.

2023-07-13 06:27 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-13 06:40 UTC, JeevakaPrabu requested changes
could you please rewrite the commit message?

Fix for VTS test case SuspendSepolicyTests failing

Android-T added new VTS test case for suspend which verifies genfs
rules. VTS test case is failing due to  missing device/oem specific
selinux genfscon rules for suspend.

Fix the issue by adding device specific genfscon rules.

Tracked-On: OAM-111173
Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>

2023-07-13 06:42 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-13 06:42 UTC, sysopenci commented
Improper Commit Message
Jira issue not in ['bug','improvement'],
    make sure jira issue is of type bug or improvement.

2023-07-13 08:45 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-14 03:15 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-14 04:28 UTC, JeevakaPrabu approved these changes

2023-07-14 04:38 UTC, ceiba1985 approved these changes

2023-07-14 05:30 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-14 10:45 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/5187

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2023-07-15 11:51 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/5189

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2023-07-17 09:42 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/5190

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2023-07-17 10:30 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/3017

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2023-07-17 14:02 UTC, merged

2023-07-17 14:03 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/3376

2023-07-19 08:37 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details