Enable SELinux for ivi
projectceladon/device-intel-sepolicy pull request #244
Opened 2023-09-12 06:23 UTC by ceiba1985

Add some essential sepolicy rules for ivi, so that ivi devices can boot up with SELinux in enforcing mode.

Tracked-On: OAM-112152

2023-09-12 06:25 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-12 09:57 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-09-15 06:54 UTC, JeevakaPrabu requested changes
Better to detail the permissions added instead of "Add some essential sepolicy rules for ivi, so that ivi devices can boot up with SELinux in enforcing mode."

For eg:
- Added permissions for EVS service to send ioctl to video device
- Added permission to allow system_server access to graphics device
....
....

2023-09-15 07:26 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-15 07:47 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-09-15 08:49 UTC, cchen113 approved these changes
LGTM.

2023-09-15 08:51 UTC, JeevakaPrabu approved these changes

2023-09-15 08:54 UTC, kwang13 approved these changes

2023-09-15 13:19 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (celadon_ivi), build-cels - r2 (r2_apollo_ivi), build-cels - r2 (r2_blizzard_ivi) - extra, build-cels - r2 (r2_celadon_ivi)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/581

2023-09-16 09:20 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (celadon_ivi), build-cels - r2 (r2_apollo_ivi), build-cels - r2 (r2_blizzard_ivi) - extra, build-cels - r2 (r2_celadon_ivi)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/584

2023-09-17 06:44 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (celadon_ivi), build-cels - r2 (r2_apollo_ivi), build-cels - r2 (r2_blizzard_ivi) - extra, build-cels - r2 (r2_celadon_ivi)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/586

2023-09-17 20:25 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (celadon_ivi), build-cels - r2 (r2_apollo_ivi), build-cels - r2 (r2_blizzard_ivi) - extra, build-cels - r2 (r2_celadon_ivi)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/587

2023-09-18 03:54 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/588

Done by "Ji, Zhenlong Z" <zhenlong.z.ji@intel.com>

2023-09-18 03:56 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/357

Done by "Ji, Zhenlong Z" <zhenlong.z.ji@intel.com>

2023-09-18 05:58 UTC, merged

2023-09-18 05:59 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Ji, Zhenlong Z" <zhenlong.z.ji@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/349