Add the sepolicy support for houdini debug
projectceladon/device-intel-sepolicy pull request #273
Opened 2023-11-29 08:13 UTC by wangtao-intel

Tests:
Houdini can successfully catch debug log

Tracked-On: OAM-113667

2023-11-29 08:32 UTC, cchen113 approved these changes
LGTM.

2023-11-30 03:05 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1135

2023-11-30 04:09 UTC, JeevakaPrabu requested changes
Signed-off-by missing

2023-11-30 04:15 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-11-30 04:18 UTC, wangtao-intel commented
> Signed-off-by missing

Have added

2023-11-30 04:34 UTC, sysopenci commented
Improper Commit Message
signed off value not found in commit message

2023-11-30 04:35 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-11-30 05:01 UTC, JeevakaPrabu approved these changes

2023-11-30 09:13 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1141

Done by "Wang, Tao" <tao.wang@intel.com>

2023-11-30 09:24 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/615

Done by "Wang, Tao" <tao.wang@intel.com>

2023-11-30 12:39 UTC, merged

2023-11-30 12:40 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cactusi@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/627