sepolicy for intel evs app
projectceladon/device-intel-sepolicy pull request #336
Opened 2024-08-24 13:58 UTC by shivasku82

2024-08-24 13:58 UTC, sysopenci commented
Expected syntax:
    Commit message one-line summary

      Extra paragraphs can be added here.

      Longer description that explains the problem / solution
      or whatever that needs to be said

      It can contain
        multiple lines
        multiple paragraphs
        blank lines
        references

      But each paragraph must be followed by a blank line

      However, you need to keep the 'Tracked-On', 'Change-Id',
      'Signed-off-by', ..., fields in the **lastest** paragraph of
      the commit message.

      Change-Id: I9e58f79c7faf7f0edb9792e8b5322ab161331141
      Tracked-On: https://jira.server.ext/browse/PROJECTA-123
      Signed-off-by: Developer Name <developer.name@intel.com>

2024-08-24 14:08 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-24 16:58 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-25 15:57 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-25 17:53 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-25 17:54 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-25 17:55 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-25 18:35 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-25 20:49 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-26 07:47 UTC, neofang7 approved these changes
LGTM

2024-08-26 07:54 UTC, balajim001 approved these changes
LGTM

2024-08-26 13:38 UTC, JeevakaPrabu requested changes
- remove changes from line 34 to 51 and add only needed policies
- Add tests done to commit message and also in commit message add a Note: EVS intel app is customized version of default evs app to support virtio and ....

2024-08-26 16:32 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-26 17:24 UTC, JeevakaPrabu approved these changes

2024-08-26 19:45 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-27 02:31 UTC, ceiba1985 commented on car/file_contexts
> +/system/bin/evs_app_support_lib                                 u:object_r:evs_intel_app_exec:s0
It's not proper to put Intel's binary to system partition. It will be lost after flashing the GSI image.

2024-08-27 05:15 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-27 10:35 UTC, merged

2024-08-27 10:59 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_umr0_master-merge/35