Sepolicy for android_pm_tune script
projectceladon/device-intel-sepolicy pull request #344
Opened 2024-09-26 09:50 UTC by amarjeet-intel

Adding the required domain and rules for
executing android_pm_tune script to obtain
the power optimization during idle display
conditions.

Tests done : Logs

Tracked-On: OAM-125227

2024-10-25 07:08 UTC, kaushlen approved these changes

2024-10-29 04:38 UTC, JeevakaPrabu requested changes

2024-10-29 04:38 UTC, JeevakaPrabu commented on power/android_pm_tune.te
> +allow android_pm_tune sysfs_net:file {getattr};
getattr is part of r_file_perms so no need to separately add it

2024-10-29 04:38 UTC, JeevakaPrabu commented on power/android_pm_tune.te
> +allow android_pm_tune sysfs_app_readable:file {getattr};
same comment applies here

2024-11-06 04:38 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2024-11-18 08:34 UTC, JeevakaPrabu approved these changes

2024-11-18 08:43 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-18 08:53 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-18 09:01 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-18 09:46 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-18 10:03 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 05:12 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 08:12 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 08:14 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 08:15 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 08:29 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 09:41 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-19 15:29 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-21 05:11 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-21 19:35 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-21 22:18 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-22 02:19 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-22 03:01 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-22 03:19 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-22 06:37 UTC, merged

2024-11-22 07:03 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/828