Add sepolicy for checkavx script
projectceladon/device-intel-sepolicy pull request #66
Opened 2020-10-21 09:39 UTC by amritaintel

Tracked-On:
Signed-off-by: ahs <amrita.h.s@intel.com>

2020-10-30 01:24 UTC, ceiba1985 approved these changes

2020-11-02 05:38 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2641

2020-11-02 10:41 UTC, JeevakaPrabu requested changes

2020-11-02 10:41 UTC, JeevakaPrabu commented on avx/checkavx.te
> +allow shell checkavx_exec:file getattr;
this needs to be moved to shell.te

2020-11-02 11:20 UTC, JeevakaPrabu approved these changes

2020-11-02 11:24 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2642

2020-11-03 04:32 UTC, sgnanase approved these changes

2020-11-03 09:04 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2643

Done by "Aravapalli, Yasoda" <yasoda.aravapalli@intel.com>

2020-11-03 09:05 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1307

Done by "Aravapalli, Yasoda" <yasoda.aravapalli@intel.com>

2020-11-03 13:47 UTC, merged

2020-11-03 13:48 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Aravapalli, Yasoda" <yasoda.aravapalli@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2063